site_name: Emanuel Trandafir
theme:
  name: dracula
  logo: img/me.jpeg
  favicon: img/me.jpeg
extra_css:
  - stylesheets/extra.css
nav:
  - "--- About Me ---": index.md
  - "The Case of the Vanishing Schema Field": blog/avro-duplicate-class-mystery.md
  - "'Tidy First?' and my Post-Reading Commitments": blog/tidy-first-commitments.md
  - "Clojure Threading for Dummy Java Devs (such as myself)": blog/clojure-threading.md
  - "Less Mocks, More Functions!": blog/less-mocks-more-functions.md
  - "Java's Optional vs Kotlin: Side by Side": blog/java-optional-vs-kotlin.md
  - "Lombok's \"Lazy\" Magic and the O.O.P. Alternative": blog/lombok-lazy-oop.md
  - "Uncle Bob's Advice on Stability and Abstractions": blog/clean-code-dependency-principles.md
